name = "cf-translate"
compatibility_date = "2024-05-01"
pages_build_output_dir = "dist"

# wrangler dev 会自动加载 .env 文件中的环境变量，
# 所以通常不需要在这里重复定义 [vars] 用于本地开发，除非有特殊需求。
# 对于生产环境，环境变量将在Cloudflare Pages仪表盘中设置。